language: java
addons:
  sonarcloud:
    organization: crescoedge
    token:
      secure: rKe4rjsmw4gE8vAJqds7DYDjnP2Hk+33NVwnfMWYs7chAZssQ/F/cM0RPr/Rbr3gCZdxvbiNJ+/Ekjhfn9Ia5Vs+7H+Hplg3DaiNXwAhMi3ge6enP85KvKrhbmLGmv7bzOJhOFvmgfj5Xk5P2nhEvRTV0gTf1h3fVVIPS/RPxsmt8tXzE/BP3exvcVsQhP8s3WA1uOI8OfENB0BZyGMZh31VvqF7q0YU+1HaFDLnE7IeozN+NvGT4aBh4YCgqOUV8MK2RD+3HUlsivAbQccweLdCDnvQ1jkAC8w5Yqd0lOy73RP5zltw7Q62pn44EP458X3TTlPPWNTg/0sKSJh9hIHTO3PkBQD1hpShGrG4ZWU9rTtzSXpHqZkIYeNMFEh5XWD7G64ezDimQuew+PjDrST4krp+Iey8ZGuWeHb0lMRdnUgQv7KL+BJZg/HnXPyWR3P0O3SHDihYhVdGrqqw1QbFqUP94q8Fj9L4Qfc0BHcR6s51qZv6fSa26f8slCPCBxRs9o12j+zZ5HYldl8/O5ZJET+NyJc/HH0Ut2bWwWZYYW2+UrHQeTGWbh1Z4JbA8DOFc2Bl1uS0HHqmMIJtNzJKVxddiRvwVRRZZg7QWcfgGblHHzwRZEFd/K9U9bqKgsMP+zoQEsHDJgS0fzAZJux8cXDHCDav23Qft6APlPI=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
- mvn package
before_install:
- bash prebuild.sh
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "crescoedge"
      - git config --local user.email "crescoedge@gmail.com"
      - git tag "1.0-SNAPSHOT"
deploy:
  provider: releases
  api_key:
    secure: PCNPCan2kZYgyiaToICFqDK6IJSFsh+gLN1WfNBNknpYAAaZ9AIA+zkrBo8DCLbM4DpVjcm7tYjEd2HA6ha9pQArnxsK0kMXaR1ziKdDPqtflbvToakPffyH3Zqy7PzkddeG2wdBOWB0qI0Q7GZlJc+k80l+FLEBOYXb/ef9j4ZSAEKuuFM7xSQu5cjpdsMviONuoyUcg/YKE27WqL4z8VyT+zGm54zGTzc2JgO04JjPcUv6B8/KMPxa9fpT78vhBubFNbjrTO53P1+BWIcCGWK+iedLmG/XFizjfz+KDpM2pHLRBgphabXzBXTkzWJzwTnxfg0fe2KJUPRUD6H8ub30l26aIKC6NteQrD3btweyNSTZ7yDtCKB0M5MRiwXCf7B7KdpnTjblaE04sZhR+4DzURJtc9gATl/LPagplixdnLboTaAEf+gupd7i/+fzt1FrqXTdpwQhM9b7eKbBGXl1BkJNL+QxmEgE+xq6iSk8VIqxPoZNEdwVxIv4ms3lbKheUEupg9PWjObEVZhPM9z9+WvB3tv4b+tULVFp0MefpcY/kcOFKmWi8eTHSRiQNKyL7jrH/3tC7akvJ+GDqQv1H3bHhGWQ29ERJzZUl5HwIveUkUABGcedhUB9d0rVzaPH0xnqakfkDJ3zJtz3KBEfuYu1Qb73QArpNiN0BZ4=
  file: "target/agent-1.0-SNAPSHOT.jar"
  skip_cleanup: true
