os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.3
language: java
addons:
  sonarcloud:
    organization: crescoedge
    token:
      secure: rKe4rjsmw4gE8vAJqds7DYDjnP2Hk+33NVwnfMWYs7chAZssQ/F/cM0RPr/Rbr3gCZdxvbiNJ+/Ekjhfn9Ia5Vs+7H+Hplg3DaiNXwAhMi3ge6enP85KvKrhbmLGmv7bzOJhOFvmgfj5Xk5P2nhEvRTV0gTf1h3fVVIPS/RPxsmt8tXzE/BP3exvcVsQhP8s3WA1uOI8OfENB0BZyGMZh31VvqF7q0YU+1HaFDLnE7IeozN+NvGT4aBh4YCgqOUV8MK2RD+3HUlsivAbQccweLdCDnvQ1jkAC8w5Yqd0lOy73RP5zltw7Q62pn44EP458X3TTlPPWNTg/0sKSJh9hIHTO3PkBQD1hpShGrG4ZWU9rTtzSXpHqZkIYeNMFEh5XWD7G64ezDimQuew+PjDrST4krp+Iey8ZGuWeHb0lMRdnUgQv7KL+BJZg/HnXPyWR3P0O3SHDihYhVdGrqqw1QbFqUP94q8Fj9L4Qfc0BHcR6s51qZv6fSa26f8slCPCBxRs9o12j+zZ5HYldl8/O5ZJET+NyJc/HH0Ut2bWwWZYYW2+UrHQeTGWbh1Z4JbA8DOFc2Bl1uS0HHqmMIJtNzJKVxddiRvwVRRZZg7QWcfgGblHHzwRZEFd/K9U9bqKgsMP+zoQEsHDJgS0fzAZJux8cXDHCDav23Qft6APlPI=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
- mvn package
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t docker.io/crescoedgecomputing/quickstart .
- docker push docker.io/crescoedgecomputing/quickstart
- docker build -t docker.io/crescoedgecomputing/quickstart:arm32v6 -f Dockerfile.arm32v6 .
- docker push docker.io/crescoedgecomputing/quickstart:arm32v6
- docker build -t docker.io/crescoedgecomputing/quickstart:arm32v7 -f Dockerfile.arm32v7 .
- docker push docker.io/crescoedgecomputing/quickstart:arm32v7
- docker build -t docker.io/crescoedgecomputing/quickstart:arm64v8 -f Dockerfile.arm64v8 .
- docker push docker.io/crescoedgecomputing/quickstart:arm64v8
- bash <(curl -s https://codecov.io/bash)
before_install:
- bash prebuild.sh
before_deploy:
- git config --local user.name "crescoedge"
- git config --local user.email "crescoedge@gmail.com"
- git tag "1.0-SNAPSHOT" --force
deploy:
  provider: releases
  api_key:
    secure: PCNPCan2kZYgyiaToICFqDK6IJSFsh+gLN1WfNBNknpYAAaZ9AIA+zkrBo8DCLbM4DpVjcm7tYjEd2HA6ha9pQArnxsK0kMXaR1ziKdDPqtflbvToakPffyH3Zqy7PzkddeG2wdBOWB0qI0Q7GZlJc+k80l+FLEBOYXb/ef9j4ZSAEKuuFM7xSQu5cjpdsMviONuoyUcg/YKE27WqL4z8VyT+zGm54zGTzc2JgO04JjPcUv6B8/KMPxa9fpT78vhBubFNbjrTO53P1+BWIcCGWK+iedLmG/XFizjfz+KDpM2pHLRBgphabXzBXTkzWJzwTnxfg0fe2KJUPRUD6H8ub30l26aIKC6NteQrD3btweyNSTZ7yDtCKB0M5MRiwXCf7B7KdpnTjblaE04sZhR+4DzURJtc9gATl/LPagplixdnLboTaAEf+gupd7i/+fzt1FrqXTdpwQhM9b7eKbBGXl1BkJNL+QxmEgE+xq6iSk8VIqxPoZNEdwVxIv4ms3lbKheUEupg9PWjObEVZhPM9z9+WvB3tv4b+tULVFp0MefpcY/kcOFKmWi8eTHSRiQNKyL7jrH/3tC7akvJ+GDqQv1H3bHhGWQ29ERJzZUl5HwIveUkUABGcedhUB9d0rVzaPH0xnqakfkDJ3zJtz3KBEfuYu1Qb73QArpNiN0BZ4=
  file: target/agent-1.0-SNAPSHOT.jar
  skip_cleanup: true
env:
  global:
  - secure: gbaYDeYOJSF5MiHPGJLr/iUCE7xArLGDIoQUknxvxGCPEruzwKhIFqa87jAC2PwoFLdfLdWKoRUjglyiVmylLI3TOVpgdg0STK0T+eJFPqguVjk/B9tlqJ5wnxGsduBh78NlfnqSOknJQ9FZXNi8oMYzFuJVu7FwuFynhcV7pW8/TwbK9L0rkkszJme5/g5yC5eoowXaLJjfjDdgtWEcJCM2AYUnpDiz6JSWFPuSnDuWnn8xU+7cgezNC2ptw5bV6EbPNt4a1CalxE/OBPobigwvljlY2mnHwHGgUw7ksAh0fNS0Ien9jc/b/NmcRW/uecMwK8d3SiGjbNhSCHzMDyBlcq/bEaq5Xl0b1G3Zlog5P2mrC408bqkdfxFL5h6LZIVbQjyRzLeIOYvlWJ5P/mnvdymakGc7maYZxkvtNrrtzWOOxJoXrkA67cGdvqDB9+VQf042PGdOuaZZu4dizuqYhOZTS7qXwWzUL6gcqMPdPZd6pcky2PDD7LFD5R+6VIm3a4b5gSC8F15NeP+lVq/Zf/45srnuu6YFPmOjBRqtLizTS0NEHXwrPwWEQAX+GJnfMD7Az0mL1iQGUCH9zPBgSxLhZlIt2okhqcdgPQhu841VaqEMi/fAPPv2z4pxOPYxBWGcYNOpV5hoiNjVuL4gog/Zz/PXjpV9H6lKqHc=
  - secure: Srtd4pLFfFirMVvponCeHwWA38HgA1SEXy1J7bP18+KpxAkphBrhKR5K6IEHukFluWquFFq11WcYHZLG/E5a0nO7n3EP1dENmsre5y4+zLtxhh7BYmsjW8L2SVqrBkO5ys3thePZ7+5SERv8BGRqGOcsRZOeKwnAXSOKR3xOUHBSkUkZaZrnjPvfX7py9cZCZqd7+9gMeWdyZzJ8qQbL7Aj2tiC7/RX/N2ibjPnCmZXBllzSpv2PnYfeLwFAXgsvhKLoo/xHACbyEimsUZMTlsHfb5qe7LBUfcCh0WGxDSE8VSupipZAkinNwvEz6WYvPOFG5KdUzf15Fnygn3QBZ40udshH1mkGjpP+p5i42qkGFiBsrCi57j/fkBLNUSCGigAUEE0Q9zsAqt4ohUqXho4IVG4obvCx7UA61SgzVoX85ygsOnPw2+3NiKq9Fq5zYlu9VHTBU+B+jyc5VW63ACcL+44QfQREBl3rUvjLuhrmLpNp1EpugIfH5IiuK6K/fpNdzETeNvna+HGG/I7qTn+p6xc085lUvJhSiw07+VaOQvNu8GZmTzpI6+8vLBYbNVQuU4XXv2qMyEBP51PxqaajKUuy9iif+B8BSrOLA88DWekUuUdKTwBc0oblnVvc8Mln3/MQdl8qUdrr/btSuQ0OilUWdvamflEafmP2PRI=
