matrix:
  include:
    - os: linux
      dist: bionic

language: java

script:
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn package -Dmaven.test.skip=true

after_success:
#- mvn package -Dmaven.test.skip=true
#- mvn jfx:native
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t docker.io/crescoedgecomputing/quickstart .
- docker push docker.io/crescoedgecomputing/quickstart
- bash <(curl -s https://codecov.io/bash)

before_install:
- bash prebuild.sh

before_deploy:
- git config --local user.name "crescoedge"
- git config --local user.email "crescoedge@gmail.com"
- git tag "1.1-SNAPSHOT" --force

deploy:
  provider: releases
  api_key:
    secure: PCNPCan2kZYgyiaToICFqDK6IJSFsh+gLN1WfNBNknpYAAaZ9AIA+zkrBo8DCLbM4DpVjcm7tYjEd2HA6ha9pQArnxsK0kMXaR1ziKdDPqtflbvToakPffyH3Zqy7PzkddeG2wdBOWB0qI0Q7GZlJc+k80l+FLEBOYXb/ef9j4ZSAEKuuFM7xSQu5cjpdsMviONuoyUcg/YKE27WqL4z8VyT+zGm54zGTzc2JgO04JjPcUv6B8/KMPxa9fpT78vhBubFNbjrTO53P1+BWIcCGWK+iedLmG/XFizjfz+KDpM2pHLRBgphabXzBXTkzWJzwTnxfg0fe2KJUPRUD6H8ub30l26aIKC6NteQrD3btweyNSTZ7yDtCKB0M5MRiwXCf7B7KdpnTjblaE04sZhR+4DzURJtc9gATl/LPagplixdnLboTaAEf+gupd7i/+fzt1FrqXTdpwQhM9b7eKbBGXl1BkJNL+QxmEgE+xq6iSk8VIqxPoZNEdwVxIv4ms3lbKheUEupg9PWjObEVZhPM9z9+WvB3tv4b+tULVFp0MefpcY/kcOFKmWi8eTHSRiQNKyL7jrH/3tC7akvJ+GDqQv1H3bHhGWQ29ERJzZUl5HwIveUkUABGcedhUB9d0rVzaPH0xnqakfkDJ3zJtz3KBEfuYu1Qb73QArpNiN0BZ4=
  file: target/agent-1.1-SNAPSHOT.jar
  skip_cleanup: true
env:
  global:
  - secure: gbaYDeYOJSF5MiHPGJLr/iUCE7xArLGDIoQUknxvxGCPEruzwKhIFqa87jAC2PwoFLdfLdWKoRUjglyiVmylLI3TOVpgdg0STK0T+eJFPqguVjk/B9tlqJ5wnxGsduBh78NlfnqSOknJQ9FZXNi8oMYzFuJVu7FwuFynhcV7pW8/TwbK9L0rkkszJme5/g5yC5eoowXaLJjfjDdgtWEcJCM2AYUnpDiz6JSWFPuSnDuWnn8xU+7cgezNC2ptw5bV6EbPNt4a1CalxE/OBPobigwvljlY2mnHwHGgUw7ksAh0fNS0Ien9jc/b/NmcRW/uecMwK8d3SiGjbNhSCHzMDyBlcq/bEaq5Xl0b1G3Zlog5P2mrC408bqkdfxFL5h6LZIVbQjyRzLeIOYvlWJ5P/mnvdymakGc7maYZxkvtNrrtzWOOxJoXrkA67cGdvqDB9+VQf042PGdOuaZZu4dizuqYhOZTS7qXwWzUL6gcqMPdPZd6pcky2PDD7LFD5R+6VIm3a4b5gSC8F15NeP+lVq/Zf/45srnuu6YFPmOjBRqtLizTS0NEHXwrPwWEQAX+GJnfMD7Az0mL1iQGUCH9zPBgSxLhZlIt2okhqcdgPQhu841VaqEMi/fAPPv2z4pxOPYxBWGcYNOpV5hoiNjVuL4gog/Zz/PXjpV9H6lKqHc=


