name: Java CI Cresco WSAPI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'SONATYPE CRED'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Download Dependencies
        run: bash prebuild.sh
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
